### PR TITLE
Add eurucamp 2015

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by eljojo** [comment]
yay! i don't know how to deploy, this, though. ping @skade @myabc ?

**Comment by bitboxer** [comment]
Anyone here know how to deploy this?

**Comment by myabc** [comment]
@bitboxer `rake production deploy`

**Comment by bitboxer** [comment]
I thought I don't have the permission to do that. At least I don't have the write permission on this repo.

**Pull request merged**
